---
title: "Final projects (cleaning data)"
author: "Talal Alzahrani"
date: "8/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r Variable selection}
# We excluded unnecessary variables and variables with very high missing varibles. 

# Unzip the file

unzip("samadult.csv.zip")

# 1-Read csv file
adultfile <- data.frame(read.csv("samadult.csv"))

# 2-Select variables
ad <- c( "MIEV", "REGION", "SEX", "MRACRPI2", "AGE_P", "R_MARITL", "ONEJOB", "WRKLYR4", "HYPEV", "ALDURA9", "CHLEV",
        "STREV", "EPHEV", "JAWP", "WEA", "CHE", "ARM", "BRTH", "FACE", "SPEAKING", "EYE", "WALKING", "HEADACHE",
        "COPDEV", "ASPMEDEV", "AASMEV", "ULCEV", "CANEV", "ALDURA12", "PREGEVER", "DBHVPAN", "DBHVCLN", "DBHVWLN",
        "DIBEV1", "ALDURA10", "ALCHRC17", "ALDURA17", "ALCHRC18", "ALDURA18", "ALCHRC19", "ALDURA19", "INSLN1",
        "EPILEP1", "AHAYFYR", "SINYR", "CBRCHYR", "KIDWKYR", "ALCHRC3", "ALCHRC4", "ALCHRC2","ALCHRC1",
        "VIM_DREV", "VIM_CAEV", "VIM_GLEV", "VIM_MDEV", "LUPPRT", "WKDAYR", "FLA1AR", "ALCHRC13","ALDURA13",
        "LIVEV","AWEBUSE", "AINDPRCH", "BMI", "ALCSTAT", "VIGMIN", "MODMIN", "MODFREQW", "SMKSTAT2", "ALCHRONR",
        "ALCHRC33", "ALDURA33", "ALCHRC30", "ALDURA30", "ALCHRC29", "ALDURA29") # the name of selected variables

adult <- adultfile[c(ad)] # select variables to the new dataset

rm(ad,adultfile) # remove the old dataset

adult[is.na(adult)] <- 0 # replace na with 0. 


# Change the outcome to a binary data (0=did not have heart attack and 1= had heart attack)
adult$MIEV[adult$MIEV == 2 | adult$MIEV == 7 | adult$MIEV == 9] <- 0

# Change BMI to the correcto values. For instance, 2500 -> 25.00
adult$BMI <- adult$BMI/100

```


```{r generate a new csv file with clean data}
write.csv(adult,"adult.csv")
```
